language: scala

sudo: required

dist: trusty

git:
  depth: 9999

scala:
  - 2.10.6
  - 2.11.11
  - 2.12.2

jdk:
  - oraclejdk7
  - oraclejdk8

matrix:
  exclude:
  - scala: 2.12.2
    jdk: oraclejdk7
  - scala: 2.10.6
    jdk: oraclejdk8
  - scala: 2.11.11
    jdk: oraclejdk7

before_install:
 - export PATH=${PATH}:./vendor/bundle

script:
  - scripts/travis-publish.sh

# http://austinpray.com/ops/2015/09/20/change-travis-node-version.html
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - pip install --user codecov
  - gem install jekyll -v 2.5

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/2d5ea16a2f66f60a590b
    on_success: change
    on_failure: always
    on_start: false

env:
  matrix:
    - JS_BUILD=false
    - JS_BUILD=true
  global:
  - TRAVIS_NODE_VERSION="4"
  - secure: llKXp4ESbYJSJ6Gq19D8IdIxFVNwDwVjm6HirsZEplyYSlHGKZWtMwdzRjemY+E83yGY/w53jFfmax
  - secure: CwsCQUmbZQd09NNqdqInw6Fczzpv3oJk4oN0gcOqNN5cw+o4nsnDb69lh6dPBRR7OI9WXtSp2BS+1Q

cache:
  directories:
  - $HOME/.sbt/0.13/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
  - $HOME/.nvm

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

after_success:
  - "[[ $TRAVIS_BRANCH == \"master\" ]] && { sbt publish; };"
